name: Docker workflow
on:
  workflow_call:
    inputs:
      IMAGE_REPOSITORY:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true

env:
  IMAGE_REPOSITORY: ${{ inputs.IMAGE_REPOSITORY }}

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: prepare
        id: before_script
        run: |
          #!/bin/bash

          printenv
          if [[ "$IMAGE_REPOSITORY" == "" ]]; then
            echo "IMAGE_REPOSITORY must be define."
            echo "IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}"
            printenv
            exit 1
          fi

          IMAGE_TAG=m-$(echo ${GITHUB_SHA::7})
          echo "::set-output name=IMAGE_URL::${IMAGE_REPOSITORY}:${IMAGE_TAG}"

      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.before_script.outputs.IMAGE_URL }}

