name: Docker workflow
on:
  workflow_call:
    inputs:
      IMAGE_REPOSITORY:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true

env:
  IMAGE_REPOSITORY: ${{ inputs.IMAGE_REPOSITORY }}

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - run: |
          #!/bin/bash

          if [[ "$IMAGE_REPOSITORY" == "" ]]; then
            echo "IMAGE_REPOSITORY must be define."
            echo "IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}"
            printenv
            exit 1
          fi

          export IMAGE_TAG=m-$(echo ${GITHUB_SHA::7})

      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: printenv
